version: '3'

services:
  development:
    build: 
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js